# Generated by Django 5.2.15 on 2026-06-16 20:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0002_crop_market_priceentry_region_userprofile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='approved', help_text='Agents require admin approval; others are auto-approved', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='assigned_market',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_agents', to='prices.market'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='crops_of_interest',
            field=models.TextField(blank=True, help_text='Comma-separated crop names'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='district',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='experience',
            field=models.TextField(blank=True, help_text='Experience description'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='farm_size',
            field=models.FloatField(blank=True, help_text='Farm size in acres', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='id_verification',
            field=models.TextField(blank=True, help_text='ID verification document reference'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='main_crops',
            field=models.TextField(blank=True, help_text='Comma-separated list of crops grown'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='operating_regions',
            field=models.TextField(blank=True, help_text='Comma-separated regions of operation'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='preferred_markets',
            field=models.TextField(blank=True, help_text='Comma-separated market names'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='transport_capacity',
            field=models.CharField(blank=True, help_text='e.g. 5 tons, pickup truck', max_length=100),
        ),
    ]
