# Generated by Django 5.2.15 on 2026-06-17 09:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0003_userprofile_approval_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='market',
            name='district',
            field=models.CharField(blank=True, help_text='District the market is in', max_length=100),
        ),
        migrations.AddField(
            model_name='market',
            name='governing_authority',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='market',
            name='market_type',
            field=models.CharField(choices=[('daily', 'Daily market'), ('periodic', 'Periodic / Weekly market'), ('wholesale', 'Wholesale market'), ('mixed', 'Mixed retail and wholesale')], default='daily', max_length=20),
        ),
        migrations.AddField(
            model_name='market',
            name='operating_days',
            field=models.TextField(blank=True, help_text='Comma-separated: Mon, Tue, Wed, Thu, Fri, Sat, Sun'),
        ),
        migrations.AddField(
            model_name='market',
            name='ward',
            field=models.CharField(blank=True, help_text='Ward / area of the market', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='appointment_document',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='authority_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='authority_type',
            field=models.CharField(blank=True, choices=[('lga', 'Local Government Authority (LGA)'), ('district', 'District council'), ('tmx', 'Tanzania Mercantile Exchange (TMX)'), ('eagc', 'Eastern Africa Grain Council (EAGC)'), ('private', 'Private market operator'), ('cooperative', 'Cooperative / Farmers association'), ('other', 'Other')], max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='avg_harvest_qty',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='avg_harvest_unit',
            field=models.CharField(blank=True, choices=[('bags', 'Bags'), ('tonnes', 'Tonnes'), ('kilograms', 'Kilograms')], max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='avg_monthly_volume',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bank_account_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bank_account_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='brela_number',
            field=models.CharField(blank=True, help_text='BRELA registration number', max_length=50),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='business_licence_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='business_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='commission_mobile_money_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='commission_mobile_money_provider',
            field=models.CharField(blank=True, choices=[('mpesa', 'Vodacom M-Pesa'), ('tigo', 'Tigo Pesa'), ('airtel', 'Airtel Money'), ('halopesa', 'Halopesa'), ('none', 'None')], max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='commitment_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='contact_person_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='contact_person_role',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='cooperative_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='crop_board_permits',
            field=models.TextField(blank=True, help_text='Comma-separated: coffee, cashew, cotton, tea, sisal'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='crops_at_market',
            field=models.TextField(blank=True, help_text='Comma-separated crop names at market'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='earns_commission',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='entity_type',
            field=models.CharField(blank=True, choices=[('individual', 'Individual trader'), ('business', 'Business entity')], max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='export_licence_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='farm_size_unit',
            field=models.CharField(blank=True, choices=[('acres', 'Acres'), ('hectares', 'Hectares')], default='acres', max_length=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='farming_type',
            field=models.CharField(blank=True, choices=[('subsistence', 'Subsistence (for household use)'), ('commercial', 'Commercial (for sale)'), ('mixed', 'Mixed (both)')], max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Prefer not to say')], max_length=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='guidelines_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='has_export_licence',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='has_transport',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_officially_appointed',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='land_ownership',
            field=models.CharField(blank=True, choices=[('owned', 'Owned outright'), ('family', 'Family land (shared)'), ('rented', 'Rented / leased'), ('cooperative', 'Cooperative land'), ('government', 'Government-allocated')], max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='market_type',
            field=models.CharField(blank=True, help_text='daily, periodic, wholesale, mixed', max_length=50),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='mobile_money_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='mobile_money_provider',
            field=models.CharField(blank=True, choices=[('mpesa', 'Vodacom M-Pesa'), ('tigo', 'Tigo Pesa'), ('airtel', 'Airtel Money'), ('halopesa', 'Halopesa'), ('none', 'None')], max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='nida_number',
            field=models.CharField(blank=True, help_text='National ID number (20 digits)', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='official_agent_id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='operating_days',
            field=models.TextField(blank=True, help_text='Comma-separated: Mon, Tue, Wed...'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('mobile_money', 'Mobile Money'), ('bank', 'Bank Transfer')], max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='price_collection_methods',
            field=models.TextField(blank=True, help_text='Comma-separated: observation, sellers, buyers, board, records'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='primary_sales_region',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='primary_source_region',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profile_photo',
            field=models.URLField(blank=True, help_text='URL to uploaded profile photo'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='referee_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='referee_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='referee_relationship',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='reporting_frequency',
            field=models.CharField(blank=True, choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('as_available', 'As available')], max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='supervisor_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='supervisor_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='supervisor_title',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='supporting_document',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='tin_number',
            field=models.CharField(blank=True, help_text='Tax Identification Number', max_length=50),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='trade_types',
            field=models.TextField(blank=True, help_text='Comma-separated: wholesale, retail, exporter, importer, broker, processor'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='trading_since_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='vehicle_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='vehicle_types',
            field=models.TextField(blank=True, help_text='Comma-separated: lorry, pickup, motorbike'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='volume_unit',
            field=models.CharField(blank=True, choices=[('bags', 'Bags'), ('tonnes', 'Tonnes'), ('kilograms', 'Kilograms')], max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='ward',
            field=models.CharField(blank=True, help_text='Ward / Village name', max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('suspended', 'Suspended')], default='approved', help_text='Agents require admin approval; others are auto-approved', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='farm_size',
            field=models.FloatField(blank=True, help_text='Farm size', null=True),
        ),
        migrations.CreateModel(
            name='MarketAgentSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('published', 'Published'), ('under_review', 'Under Review'), ('flagged', 'Flagged'), ('live', 'Live')], default='published', max_length=20)),
                ('agent_notes', models.TextField(blank=True, help_text='Notes from agent, especially for flagged submissions')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('under_review_at', models.DateTimeField(blank=True, null=True)),
                ('flagged_at', models.DateTimeField(blank=True, null=True)),
                ('live_at', models.DateTimeField(blank=True, null=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_submissions', to=settings.AUTH_USER_MODEL)),
                ('price_entry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agent_submission', to='prices.priceentry')),
            ],
            options={
                'verbose_name_plural': 'Agent submissions',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='TransportRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance_km', models.FloatField(help_text='Approximate distance in kilometers')),
                ('base_cost_tzs', models.FloatField(help_text='Base transport cost in TZS')),
                ('cost_per_kg', models.FloatField(default=0, help_text='Additional cost per kg of produce')),
                ('vehicle_costs', models.TextField(blank=True, help_text='Comma-separated vehicle:cost pairs, e.g. lorry:50000,pickup:30000,motorbike:5000')),
                ('estimated_hours', models.FloatField(blank=True, help_text='Estimated travel time in hours', null=True)),
                ('road_quality', models.CharField(blank=True, help_text='tarmac, gravel, dirt', max_length=20)),
                ('is_seasonal', models.BooleanField(default=False, help_text='True if route is only passable in certain seasons')),
                ('destination_market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes_to', to='prices.market')),
                ('origin_market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes_from', to='prices.market')),
            ],
            options={
                'ordering': ['origin_market__name', 'destination_market__name'],
                'unique_together': {('origin_market', 'destination_market')},
            },
        ),
    ]
