# Generated by Django 5.2.15 on 2026-06-17 23:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0004_market_district_market_governing_authority_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('price_drop', 'Price Drop'), ('price_rise', 'Price Rise'), ('above_threshold', 'Above Price Threshold'), ('below_threshold', 'Below Price Threshold')], max_length=20)),
                ('threshold_price', models.FloatField(blank=True, help_text='Price threshold for above/below alerts (TZS)', null=True)),
                ('pct_change', models.FloatField(blank=True, help_text='Percentage change to trigger alert (e.g. 10 for 10%)', null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('triggered', 'Triggered'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('triggered_at', models.DateTimeField(blank=True, null=True)),
                ('last_checked', models.DateTimeField(blank=True, null=True)),
                ('triggered_price', models.FloatField(blank=True, help_text='Price that triggered the alert', null=True)),
                ('message', models.TextField(blank=True, help_text='Notification message when triggered')),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_alerts', to='prices.crop')),
                ('market', models.ForeignKey(blank=True, help_text='Leave blank to monitor all markets', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='price_alerts', to='prices.market')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
