# Generated by Django 5.2.15 on 2026-06-18 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0005_add_price_alert'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email_code_sent_at',
            field=models.DateTimeField(blank=True, help_text='When the verification code was sent', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='email_verification_code',
            field=models.CharField(blank=True, help_text='6-digit email verification code', max_length=6),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='email_verified',
            field=models.BooleanField(default=False, help_text='Whether the user has verified their email'),
        ),
    ]
