# Generated by Django 5.2.15 on 2026-06-20 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0007_cooperative_marketmatch_cooperativemembership'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(choices=[('truck', 'Truck / Lorry'), ('bus', 'Bus / Express Bus'), ('pickup', 'Pickup Truck'), ('motorbike', 'Motorbike'), ('bicycle', 'Bicycle')], max_length=20, unique=True)),
                ('base_rate_per_km', models.FloatField(default=200.0, help_text='Base rate in TZS per km per ton')),
                ('vehicle_multiplier', models.FloatField(default=1.0, help_text='Vehicle type multiplier: truck=1.0, bus=1.3, pickup=0.8, motorbike=0.3')),
                ('fuel_multiplier', models.FloatField(default=1.0, help_text='Fuel price adjustment factor')),
                ('min_charge', models.FloatField(default=5000.0, help_text='Minimum charge in TZS regardless of distance')),
                ('large_cargo_threshold_kg', models.FloatField(default=5000.0, help_text='Cargo above this gets volume discount')),
                ('large_cargo_discount', models.FloatField(default=0.9, help_text='Discount factor for large cargo (0.9 = 10% off)')),
            ],
        ),
        migrations.CreateModel(
            name='RegionRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance_km', models.FloatField(help_text='Road distance in kilometers')),
                ('road_type', models.CharField(choices=[('trunk', 'Trunk Road (National Highway)'), ('regional', 'Regional Road'), ('district', 'District Road')], default='trunk', max_length=20)),
                ('corridor', models.CharField(choices=[('northern', 'Northern Corridor (Dar → Arusha → Kenya)'), ('central', 'Central Corridor (Dar → Dodoma → Mwanza → Kigoma)'), ('southern', 'Southern Corridor (Dar → Mbeya → Tunduma)'), ('lake', 'Lake Corridor (Arusha → Mwanza → Kagera)'), ('western', 'Western Corridor (Arusha → Katavi)'), ('coastal', 'Coastal Corridor (Tanga → Dar → Mtwara)'), ('none', 'Not on a major corridor')], default='none', max_length=20)),
                ('condition_factor', models.FloatField(default=1.0, help_text='Road condition multiplier: 1.0=good, 1.1=fair, 1.2-1.4=poor/remote')),
                ('avg_speed_kmh', models.FloatField(default=60.0, help_text='Average speed in km/h: trunk=60, regional=40, district=30')),
                ('is_bidirectional', models.BooleanField(default=True, help_text='If True, route works both ways (most roads)')),
                ('from_region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes_from', to='prices.region')),
                ('to_region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes_to', to='prices.region')),
            ],
            options={
                'ordering': ['from_region__name', 'to_region__name'],
                'unique_together': {('from_region', 'to_region')},
            },
        ),
    ]
