# Generated by Django 5.2.15 on 2026-06-26 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0013_magiclink_phoneverification_onboarding'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='notification',
            new_name='prices_noti_user_id_a57d03_idx',
            old_name='prices_noti_user_id_1a2b3c_idx',
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='prices_noti_user_id_c7131f_idx',
            old_name='prices_noti_user_id_4d5e6f_idx',
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='prices_noti_type_7cb7e8_idx',
            old_name='prices_noti_type_7g8h9i_idx',
        ),
        migrations.AlterField(
            model_name='pricingrule',
            name='base_rate_per_km',
            field=models.FloatField(default=1.85, help_text='Base rate: TSH per km per kg (truck/bus/pickup) or TSH per km (motorcycle)'),
        ),
        migrations.AlterField(
            model_name='pricingrule',
            name='vehicle_multiplier',
            field=models.FloatField(default=1.0, help_text='Vehicle type multiplier applied to base rate'),
        ),
        migrations.AlterField(
            model_name='pricingrule',
            name='vehicle_type',
            field=models.CharField(choices=[('truck', 'Truck / Lorry'), ('bus', 'Bus / Express Bus'), ('pickup', 'Pickup Truck'), ('motorcycle', 'Motorcycle (Bodaboda)'), ('bicycle', 'Bicycle')], max_length=20, unique=True),
        ),
    ]
