# Generated by Django 5.2.15 on 2026-06-27 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0015_userprofile_failed_login_attempts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='priceentry',
            name='latitude',
            field=models.FloatField(blank=True, help_text='GPS latitude at submission', null=True),
        ),
        migrations.AddField(
            model_name='priceentry',
            name='longitude',
            field=models.FloatField(blank=True, help_text='GPS longitude at submission', null=True),
        ),
    ]
