# Generated by Django 5.2.15 on 2026-06-27
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0016_add_gps_to_priceentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='sms_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notification',
            name='whatsapp_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notification',
            name='delivery_attempted',
            field=models.DateTimeField(null=True, blank=True),
        ),
    ]
