# Generated by Django 6.0.6 on 2026-06-29 05:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0017_add_notification_delivery_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='CropCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season_name', models.CharField(blank=True, help_text='e.g. Masika, Vuli, Main Season', max_length=100)),
                ('planting_start', models.IntegerField(blank=True, help_text='Planting start month (1-12)', null=True)),
                ('planting_end', models.IntegerField(blank=True, help_text='Planting end month (1-12)', null=True)),
                ('harvest_start', models.IntegerField(blank=True, help_text='Harvest start month (1-12)', null=True)),
                ('harvest_end', models.IntegerField(blank=True, help_text='Harvest end month (1-12)', null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the season')),
                ('source', models.CharField(blank=True, help_text='Source of the data', max_length=200)),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendars', to='prices.crop')),
                ('region', models.ForeignKey(blank=True, help_text='Leave blank for national calendar', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calendars', to='prices.region')),
            ],
            options={
                'verbose_name_plural': 'Crop calendars',
                'ordering': ['crop', 'region', 'harvest_start'],
                'unique_together': {('crop', 'region', 'season_name')},
            },
        ),
    ]
