# Generated by Django 6.0.6 on 2026-06-29 05:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0018_cropcalendar'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('scraper_command', models.CharField(help_text='e.g. kilimo_pdfs/scrape_all.py --source kilimo', max_length=300)),
                ('update_interval_seconds', models.IntegerField(default=86400, help_text='How often to check for new data')),
                ('is_active', models.BooleanField(default=True)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('last_status', models.CharField(choices=[('never', 'Never'), ('running', 'Running'), ('success', 'Success'), ('partial', 'Partial'), ('failed', 'Failed')], default='never', max_length=20)),
                ('last_items_found', models.IntegerField(default=0)),
                ('last_items_imported', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('running', 'Running'), ('success', 'Success'), ('partial', 'Partial'), ('failed', 'Failed')], default='running', max_length=20)),
                ('items_found', models.IntegerField(default=0)),
                ('items_imported', models.IntegerField(default=0)),
                ('items_skipped', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='prices.syncsource')),
            ],
            options={
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['source', '-started_at'], name='prices_sync_source__815855_idx'), models.Index(fields=['status'], name='prices_sync_status_d29b7b_idx')],
            },
        ),
    ]
