# Generated by Django 6.0.6 on 2026-06-29 06:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0019_syncsource_synclog'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('temp_max', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('temp_min', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('precipitation', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True)),
                ('humidity', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('wind_speed', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('weather_code', models.IntegerField(blank=True, null=True)),
                ('fetched_at', models.DateTimeField(auto_now=True)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weather_data', to='prices.region')),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['region', '-date'], name='prices_weat_region__a4d881_idx')],
                'unique_together': {('region', 'date')},
            },
        ),
    ]
