# Generated by Django 5.2.15 on 2026-06-29 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prices', '0020_weatherdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='weatherdata',
            name='apparent_temp',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Apparent/feels-like temperature (°C)', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='weatherdata',
            name='cloud_cover',
            field=models.IntegerField(blank=True, help_text='Total cloud cover (%)', null=True),
        ),
        migrations.AddField(
            model_name='weatherdata',
            name='dew_point',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Dew point temperature (°C)', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='weatherdata',
            name='precipitation_probability',
            field=models.IntegerField(blank=True, help_text='Precipitation probability (%)', null=True),
        ),
        migrations.AddField(
            model_name='weatherdata',
            name='pressure',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Surface pressure (hPa)', max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='weatherdata',
            name='soil_moisture_0_1cm',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Soil moisture 0-1cm (m³/m³)', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='weatherdata',
            name='soil_moisture_1_3cm',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Soil moisture 1-3cm (m³/m³)', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='weatherdata',
            name='soil_temp_0cm',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Soil temperature at surface (°C)', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='weatherdata',
            name='soil_temp_6cm',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Soil temperature at 6cm depth (°C)', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='weatherdata',
            name='uv_index',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='UV index', max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='weatherdata',
            name='visibility',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Visibility (km)', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='weatherdata',
            name='wind_direction',
            field=models.IntegerField(blank=True, help_text='Wind direction in degrees', null=True),
        ),
        migrations.CreateModel(
            name='HourlyWeatherData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('temperature', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('precipitation', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True)),
                ('precipitation_probability', models.IntegerField(blank=True, help_text='Precipitation probability (%)', null=True)),
                ('humidity', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('wind_speed', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('wind_direction', models.IntegerField(blank=True, help_text='Wind direction in degrees', null=True)),
                ('pressure', models.DecimalField(blank=True, decimal_places=1, help_text='Surface pressure (hPa)', max_digits=7, null=True)),
                ('apparent_temp', models.DecimalField(blank=True, decimal_places=1, help_text='Apparent/feels-like temperature (°C)', max_digits=5, null=True)),
                ('uv_index', models.DecimalField(blank=True, decimal_places=1, help_text='UV index', max_digits=4, null=True)),
                ('cloud_cover', models.IntegerField(blank=True, help_text='Cloud cover (%)', null=True)),
                ('visibility', models.DecimalField(blank=True, decimal_places=1, help_text='Visibility (km)', max_digits=6, null=True)),
                ('weather_code', models.IntegerField(blank=True, null=True)),
                ('fetched_at', models.DateTimeField(auto_now=True)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hourly_weather', to='prices.region')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['region', '-timestamp'], name='prices_hour_region__f12379_idx')],
                'unique_together': {('region', 'timestamp')},
            },
        ),
    ]
